In [12]:
def selectByDate(S,strat, end):#S: dataset, strat =2020-05-21 and end = 2020-05-23, will return the data in 2020-05-22
    return S[(S["Date"] > strat) & (S["Date"] < end )]
def selectByConfirmed(S,min_num, max_num):
    return S[(S["Confirmed"] > min_num) & (S["Confirmed"] < max_num ) ]
def selectByDeath(S,min_num, max_num):
    return S[(S["Deaths"] > min_num) & (S["Deaths"] < max_num ) ]

In [13]:
import pandas as pd
file1="us_simplified.csv"
file2="COVID-19_Vaccinations_in_the_United_States_Jurisdiction.csv" 
cases = pd.read_csv(file1) #Date	Admin2	Province/State	Confirmed	Deaths	Country/Region

In [14]:

States_list = pd.unique(cases["Province/State"])
States_list

array(['Alabama', 'Alaska', 'American Samoa', 'Arizona', 'Arkansas',
       'California', 'Colorado', 'Connecticut', 'Delaware',
       'Diamond Princess', 'District of Columbia', 'Florida', 'Georgia',
       'Grand Princess', 'Guam', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Northern Mariana Islands', 'Ohio', 'Oklahoma',
       'Oregon', 'Pennsylvania', 'Puerto Rico', 'Rhode Island',
       'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah',
       'Vermont', 'Virgin Islands', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming'], dtype=object)

In [15]:
states_data = dict()
for x in States_list:
    states_data[x] = cases[cases["Province/State"] == x]

In [16]:
#set state , and city
state_name = 'Colorado'
city_name = "Boulder"

In [17]:
'''
index  ['Alabama', 'Alaska', 'American Samoa', 'Arizona', 'Arkansas',
       'California', 'Colorado', 'Connecticut', 'Delaware',
       'Diamond Princess', 'District of Columbia', 'Florida', 'Georgia',
       'Grand Princess', 'Guam', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Northern Mariana Islands', 'Ohio', 'Oklahoma',
       'Oregon', 'Pennsylvania', 'Puerto Rico', 'Rhode Island',
       'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah',
       'Vermont', 'Virgin Islands', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming']
 '''
state = states_data[state_name]
adams_list = pd.unique(state["Admin2"])
region_data = dict()
for x in adams_list:
    region_data[x] = state[(state["Admin2"] == x) ]
#datas in city 
city = region_data[city_name]

['Adams' 'Alamosa' 'Arapahoe' 'Archuleta' 'Baca' 'Bent' 'Boulder'
 'Broomfield' 'Chaffee' 'Cheyenne' 'Clear Creek' 'Conejos' 'Costilla'
 'Crowley' 'Custer' 'Delta' 'Denver' 'Dolores' 'Douglas' 'Eagle' 'El Paso'
 'Elbert' 'Fremont' 'Garfield' 'Gilpin' 'Grand' 'Gunnison' 'Hinsdale'
 'Huerfano' 'Jackson' 'Jefferson' 'Kiowa' 'Kit Carson' 'La Plata' 'Lake'
 'Larimer' 'Las Animas' 'Lincoln' 'Logan' 'Mesa' 'Mineral' 'Moffat'
 'Montezuma' 'Montrose' 'Morgan' 'Otero' 'Ouray' 'Out of CO' 'Park'
 'Phillips' 'Pitkin' 'Prowers' 'Pueblo' 'Rio Blanco' 'Rio Grande' 'Routt'
 'Saguache' 'San Juan' 'San Miguel' 'Sedgwick' 'Summit' 'Teller'
 'Unassigned' 'Washington' 'Weld' 'Yuma']

In [23]:
'''
cases: All data of covid19 cases in US
state(dictionary type): All data of covid19 cases in one State
city(dictionary type): All data of covid19 cases in one city
'''
print("states name:", States_list)
print("\n")
print("city names: " ,adams_list)

states name: ['Alabama' 'Alaska' 'American Samoa' 'Arizona' 'Arkansas' 'California'
 'Colorado' 'Connecticut' 'Delaware' 'Diamond Princess'
 'District of Columbia' 'Florida' 'Georgia' 'Grand Princess' 'Guam'
 'Hawaii' 'Idaho' 'Illinois' 'Indiana' 'Iowa' 'Kansas' 'Kentucky'
 'Louisiana' 'Maine' 'Maryland' 'Massachusetts' 'Michigan' 'Minnesota'
 'Mississippi' 'Missouri' 'Montana' 'Nebraska' 'Nevada' 'New Hampshire'
 'New Jersey' 'New Mexico' 'New York' 'North Carolina' 'North Dakota'
 'Northern Mariana Islands' 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania'
 'Puerto Rico' 'Rhode Island' 'South Carolina' 'South Dakota' 'Tennessee'
 'Texas' 'Utah' 'Vermont' 'Virgin Islands' 'Virginia' 'Washington'
 'West Virginia' 'Wisconsin' 'Wyoming']


city names:  ['Adams' 'Alamosa' 'Arapahoe' 'Archuleta' 'Baca' 'Bent' 'Boulder'
 'Broomfield' 'Chaffee' 'Cheyenne' 'Clear Creek' 'Conejos' 'Costilla'
 'Crowley' 'Custer' 'Delta' 'Denver' 'Dolores' 'Douglas' 'Eagle' 'El Paso'
 'Elbert' 'Fremont' 'Garfield' 'Gilpin' 'Grand' 'Gunnison' 'Hinsdale'
 'Huerfano' 'Jackson' 'Jefferson' 'Kiowa' 'Kit Carson' 'La Plata' 'Lake'
 'Larimer' 'Las Animas' 'Lincoln' 'Logan' 'Mesa' 'Mineral' 'Moffat'
 'Montezuma' 'Montrose' 'Morgan' 'Otero' 'Ouray' 'Out of CO' 'Park'
 'Phillips' 'Pitkin' 'Prowers' 'Pueblo' 'Rio Blanco' 'Rio Grande' 'Routt'
 'Saguache' 'San Juan' 'San Miguel' 'Sedgwick' 'Summit' 'Teller'
 'Unassigned' 'Washington' 'Weld' 'Yuma']

In [18]:

selectByDate(state,"2021-05-14", "2021-05-16")
selectByConfirmed(state,2000,5000)
selectByDeath(state,50,100)

              Date Admin2 Province/State  Confirmed  Deaths Country/Region
161489  2020-04-24  Adams       Colorado       1252      57             US
161490  2020-04-25  Adams       Colorado       1302      57             US
161491  2020-04-26  Adams       Colorado       1348      58             US
161492  2020-04-27  Adams       Colorado       1391      60             US
161493  2020-04-28  Adams       Colorado       1430      61             US
...            ...    ...            ...        ...     ...            ...
201683  2020-04-26   Weld       Colorado       1469      82             US
201684  2020-04-27   Weld       Colorado       1544      87             US
201685  2020-04-28   Weld       Colorado       1618      88             US
201686  2020-04-29   Weld       Colorado       1704      93             US
201687  2020-04-30   Weld       Colorado       1776      95             US

[2632 rows x 6 columns]

In [19]:
vac = pd.read_csv(file2)
# attribute detail : https://data.cdc.gov/Vaccinations/COVID-19-Vaccinations-in-the-United-States-Jurisdi/unsk-b7fc

C:\Users\will\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (4,5,6,7,9,10,11,13,14,15,16,21,22,23,24,25,27,29,31,33,35,37,39,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [20]:
vac

,Date,MMWR_week,Location,Distributed,Distributed_Janssen,Distributed_Moderna,Distributed_Pfizer,Distributed_Unk_Manuf,Dist_Per_100K,Distributed_Per_100k_12Plus,...,Additional_Doses_18Plus,Additional_Doses_18Plus_Vax_Pct,Additional_Doses_50Plus,Additional_Doses_50Plus_Vax_Pct,Additional_Doses_65Plus,Additional_Doses_65Plus_Vax_Pct,Additional_Doses_Moderna,Additional_Doses_Pfizer,Additional_Doses_Janssen,Additional_Doses_Unk_Manuf
0,10/09/2021,40,IN,"8,572,950","460,900","3,233,540","4,878,510",0,"127,342","150,270",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,10/09/2021,40,CT,"5,766,015","270,300","2,297,400","3,198,315",0,"161,727","185,644",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,10/09/2021,40,MI,"13,858,110","694,100","5,672,740","7,491,270",0,"138,763","161,235",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,10/09/2021,40,RP,"33,090","3,800","22,900","6,390",0,"184,788","216,388",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,10/09/2021,40,TN,"8,848,720","403,000","3,452,880","4,992,840",0,"129,572","151,634",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19162,12/13/2020,51,VI,975,0,0,0,0,931,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19163,12/13/2020,51,US,"13,650",0,0,0,0,4,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19164,12/13/2020,51,GU,"3,900",0,0,0,0,"2,353",0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19165,12/13/2020,51,AS,"3,900",0,0,0,0,"7,003",0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19166,12/13/2020,51,MP,"4,875",0,0,0,0,"8,570",0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0