In [130]:
import pandas as pd
import glob
file1="us_simplified.csv"
file2="COVID-19_Vaccinations_in_the_United_States_Jurisdiction.csv" 
 
cases = pd.read_csv(file1) #Date	Admin2	Province/State	Confirmed	Deaths	Country/Region
vac = pd.read_csv(file2) # attribute detail : https://data.cdc.gov/Vaccinations/COVID-19-Vaccinations-in-the-United-States-Jurisdi/unsk-b7fc

C:\Users\will\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (4,5,6,7,9,10,11,13,14,15,16,21,22,23,24,25,27,29,31,33,35,37,39,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [72]:
def selectByDate(S,strat, end):#S: dataset, strat =2020-05-21 and end = 2020-05-23, will return the data in 2020-05-22
    return S[(S["Date"] > strat) & (S["Date"] < end ) ]
def selectByConfirmed(S,min_num, max_num):
    return S[(S["Confirmed"] > min_num) & (S["Confirmed"] < max_num ) ]
def selectByDeath(S,min_num, max_num):
    return S[(S["Deaths"] > min_num) & (S["Deaths"] < max_num ) ]

In [75]:

States_list = pd.unique(cases["Province/State"])
States_list

array(['Alabama', 'Alaska', 'American Samoa', 'Arizona', 'Arkansas',
       'California', 'Colorado', 'Connecticut', 'Delaware',
       'Diamond Princess', 'District of Columbia', 'Florida', 'Georgia',
       'Grand Princess', 'Guam', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Northern Mariana Islands', 'Ohio', 'Oklahoma',
       'Oregon', 'Pennsylvania', 'Puerto Rico', 'Rhode Island',
       'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah',
       'Vermont', 'Virgin Islands', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming'], dtype=object)

In [76]:
states_data = dict()
for x in States_list:
    states_data[x] = cases[cases["Province/State"] == x]

In [77]:
#set state , and city
state_name = 'Colorado'
city_name = "Boulder"

In [78]:
'''
index  ['Alabama', 'Alaska', 'American Samoa', 'Arizona', 'Arkansas',
       'California', 'Colorado', 'Connecticut', 'Delaware',
       'Diamond Princess', 'District of Columbia', 'Florida', 'Georgia',
       'Grand Princess', 'Guam', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Northern Mariana Islands', 'Ohio', 'Oklahoma',
       'Oregon', 'Pennsylvania', 'Puerto Rico', 'Rhode Island',
       'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah',
       'Vermont', 'Virgin Islands', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming']
 '''
state = states_data[state_name]
adams_list = pd.unique(state["Admin2"])
region_data = dict()
for x in adams_list:
    region_data[x] = state[(state["Admin2"] == x) ]
#datas in city 
city = region_data[city_name]

In [105]:
'''
cases: All data of covid19 cases in US
state(dictionary type): All data of covid19 cases in one State
city(dictionary type): All data of covid19 cases in one city
'''
print("states name:", States_list)
print("\n")
print("city names: " ,adams_list)
S = states_data["Alabama"]
selectByDate(S,"2020-05-21", "2020-06-01")

states name: ['Alabama' 'Alaska' 'American Samoa' 'Arizona' 'Arkansas' 'California'
 'Colorado' 'Connecticut' 'Delaware' 'Diamond Princess'
 'District of Columbia' 'Florida' 'Georgia' 'Grand Princess' 'Guam'
 'Hawaii' 'Idaho' 'Illinois' 'Indiana' 'Iowa' 'Kansas' 'Kentucky'
 'Louisiana' 'Maine' 'Maryland' 'Massachusetts' 'Michigan' 'Minnesota'
 'Mississippi' 'Missouri' 'Montana' 'Nebraska' 'Nevada' 'New Hampshire'
 'New Jersey' 'New Mexico' 'New York' 'North Carolina' 'North Dakota'
 'Northern Mariana Islands' 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania'
 'Puerto Rico' 'Rhode Island' 'South Carolina' 'South Dakota' 'Tennessee'
 'Texas' 'Utah' 'Vermont' 'Virgin Islands' 'Virginia' 'Washington'
 'West Virginia' 'Wisconsin' 'Wyoming']


city names:  ['Adams' 'Alamosa' 'Arapahoe' 'Archuleta' 'Baca' 'Bent' 'Boulder'
 'Broomfield' 'Chaffee' 'Cheyenne' 'Clear Creek' 'Conejos' 'Costilla'
 'Crowley' 'Custer' 'Delta' 'Denver' 'Dolores' 'Douglas' 'Eagle' 'El Paso'
 'Elbert' 'Fremont' 'Garfield' 'Gilpin' 'Grand' 'Gunnison' 'Hinsdale'
 'Huerfano' 'Jackson' 'Jefferson' 'Kiowa' 'Kit Carson' 'La Plata' 'Lake'
 'Larimer' 'Las Animas' 'Lincoln' 'Logan' 'Mesa' 'Mineral' 'Moffat'
 'Montezuma' 'Montrose' 'Morgan' 'Otero' 'Ouray' 'Out of CO' 'Park'
 'Phillips' 'Pitkin' 'Prowers' 'Pueblo' 'Rio Blanco' 'Rio Grande' 'Routt'
 'Saguache' 'San Juan' 'San Miguel' 'Sedgwick' 'Summit' 'Teller'
 'Unassigned' 'Washington' 'Weld' 'Yuma']

             Date   Admin2 Province/State  Confirmed  Deaths Country/Region
121    2020-05-22  Autauga        Alabama        151       3             US
122    2020-05-23  Autauga        Alabama        156       3             US
123    2020-05-24  Autauga        Alabama        160       3             US
124    2020-05-25  Autauga        Alabama        171       3             US
125    2020-05-26  Autauga        Alabama        191       3             US
...           ...      ...            ...        ...     ...            ...
42966  2020-05-27  Winston        Alabama         77       0             US
42967  2020-05-28  Winston        Alabama         79       0             US
42968  2020-05-29  Winston        Alabama         83       0             US
42969  2020-05-30  Winston        Alabama         84       0             US
42970  2020-05-31  Winston        Alabama         86       0             US

[690 rows x 6 columns]

In [106]:
vac["Date"] = vac["Date"].apply(pd.to_datetime)
vac["Date"] = vac["Date"].dt.strftime('%Y-%m-%d')
vac

,Date,MMWR_week,Location,Distributed,Distributed_Janssen,Distributed_Moderna,Distributed_Pfizer,Distributed_Unk_Manuf,Dist_Per_100K,Distributed_Per_100k_12Plus,...,Series_Complete_Pfizer_12Plus,Series_Complete_Unk_Manuf_12Plus,Series_Complete_Janssen_18Plus,Series_Complete_Moderna_18Plus,Series_Complete_Pfizer_18Plus,Series_Complete_Unk_Manuf_18Plus,Series_Complete_Janssen_65Plus,Series_Complete_Moderna_65Plus,Series_Complete_Pfizer_65Plus,Series_Complete_Unk_Manuf_65Plus
0,2021-10-09,40,IN,"8,572,950","460,900","3,233,540","4,878,510",0,"127,342","150,270",...,"1,856,591","7,332","252,797","1,179,273","1,670,885","7,258","28,976","448,349","432,816","3,606"
1,2021-10-09,40,CT,"5,766,015","270,300","2,297,400","3,198,315",0,"161,727","185,644",...,"1,386,165",345,"205,983","881,579","1,209,636",267,"20,529","229,903","333,143",71
2,2021-10-09,40,MI,"13,858,110","694,100","5,672,740","7,491,270",0,"138,763","161,235",...,"2,880,871",905,"373,162","1,997,461","2,586,852",848,"66,618","739,590","675,621",531
3,2021-10-09,40,RP,"33,090","3,800","22,900","6,390",0,"184,788","216,388",...,"1,640",0,"2,338","11,583",387,0,227,"1,462",16,0
4,2021-10-09,40,TN,"8,848,720","403,000","3,452,880","4,992,840",0,"129,572","151,634",...,"1,779,449","7,937","202,846","1,170,006","1,626,649","7,864","33,014","446,410","416,705","4,368"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19162,2020-12-13,51,VI,975,0,0,0,0,931,0,...,0,0,0,0,0,0,0,0,0,0
19163,2020-12-13,51,US,"13,650",0,0,0,0,4,0,...,0,0,0,0,0,0,0,0,0,0
19164,2020-12-13,51,GU,"3,900",0,0,0,0,"2,353",0,...,0,0,0,0,0,0,0,0,0,0
19165,2020-12-13,51,AS,"3,900",0,0,0,0,"7,003",0,...,0,0,0,0,0,0,0,0,0,0
19166,2020-12-13,51,MP,"4,875",0,0,0,0,"8,570",0,...,0,0,0,0,0,0,0,0,0,0

In [107]:
vac_states = dict()
for x in pd.unique(vac["Location"]):
    vac_states[x] = vac[vac["Location"] == x]

In [108]:
pd.unique(vac["Location"])

array(['IN', 'CT', 'MI', 'RP', 'TN', 'GU', 'BP2', 'DD2', 'IL', 'OK', 'MH',
       'MS', 'MT', 'AS', 'PA', 'MO', 'ND', 'IA', 'MD', 'VT', 'ID', 'MN',
       'OR', 'NM', 'RI', 'WA', 'WY', 'WV', 'AK', 'AZ', 'MA', 'SD', 'NC',
       'VI', 'GA', 'DC', 'KY', 'CO', 'NE', 'WI', 'UT', 'HI', 'MP', 'PR',
       'FL', 'CA', 'VA2', 'NV', 'FM', 'IH2', 'SC', 'VA', 'AL', 'NJ', 'TX',
       'LA', 'OH', 'NH', 'DE', 'AR', 'US', 'KS', 'ME', 'NY'], dtype=object)

In [109]:
vac_states['CO']

,Date,MMWR_week,Location,Distributed,Distributed_Janssen,Distributed_Moderna,Distributed_Pfizer,Distributed_Unk_Manuf,Dist_Per_100K,Distributed_Per_100k_12Plus,...,Series_Complete_Pfizer_12Plus,Series_Complete_Unk_Manuf_12Plus,Series_Complete_Janssen_18Plus,Series_Complete_Moderna_18Plus,Series_Complete_Pfizer_18Plus,Series_Complete_Unk_Manuf_18Plus,Series_Complete_Janssen_65Plus,Series_Complete_Moderna_65Plus,Series_Complete_Pfizer_65Plus,Series_Complete_Unk_Manuf_65Plus
37,2021-10-09,40,CO,"8,414,945","378,200","3,305,640","4,731,105",0,"146,125","170,479",...,"1,867,104","1,506","266,195","1,308,372","1,634,140","1,454","24,120","343,241","342,240",533
105,2021-10-08,40,CO,"8,369,125","374,600","3,305,000","4,689,525",0,"145,329","169,551",...,"1,867,024","1,506","266,144","1,308,326","1,634,066","1,454","24,118","343,239","342,232",533
133,2021-10-07,40,CO,"8,299,095","373,500","3,297,360","4,628,235",0,"144,113","168,132",...,"1,863,732","1,500","265,467","1,307,396","1,631,172","1,448","24,079","343,125","341,467",530
211,2021-10-06,40,CO,"8,262,245","371,600","3,284,640","4,606,005",0,"143,473","167,385",...,"1,860,248","1,495","265,028","1,306,597","1,628,151","1,443","24,040","342,971","340,698",527
263,2021-10-05,40,CO,"8,254,105","371,400","3,283,000","4,599,705",0,"143,332","167,220",...,"1,857,650","1,485","264,500","1,305,998","1,625,956","1,433","24,005","342,892","340,129",521
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18884,2020-12-18,51,CO,"46,800",0,0,0,0,813,0,...,0,0,0,0,0,0,0,0,0,0
18978,2020-12-17,51,CO,"46,800",0,0,0,0,813,0,...,0,0,0,0,0,0,0,0,0,0
18996,2020-12-16,51,CO,"46,800",0,0,0,0,813,0,...,0,0,0,0,0,0,0,0,0,0
19052,2020-12-15,51,CO,"34,125",0,0,0,0,593,0,...,0,0,0,0,0,0,0,0,0,0
19158,2020-12-14,51,CO,"8,775",0,0,0,0,152,0,...,0,0,0,0,0,0,0,0,0,0

In [145]:
#hosptial data :https://healthdata.gov/Hospital/COVID-19-Reported-Patient-Impact-and-Hospital-Capa/anag-cw7u
hosp = dict()
files = glob.glob("Reported_Patient/*.csv")
for x in files:
    df = pd.read_csv(x)
    df = df.rename(columns={"collection_week": "Date"})
    df = df.drop(columns=df.columns[0])
    hosp[x[17:19]] = df

In [148]:

for x in hosp.keys():
    hosp[x]["Date"] = hosp[x]["Date"].apply(pd.to_datetime)
    hosp[x]["Date"] = hosp[x]["Date"].dt.strftime('%Y-%m-%d')

In [149]:
hosp["CO"]

,Date,state,hospital_name,city,hospital_subtype,total_beds_7_day_avg,all_adult_hospital_beds_7_day_avg,all_adult_hospital_inpatient_beds_7_day_avg,inpatient_beds_used_7_day_avg,all_adult_hospital_inpatient_bed_occupied_7_day_avg,...,total_adult_patients_hospitalized_confirmed_covid_7_day_sum,total_pediatric_patients_hospitalized_confirmed_and_suspected_covid_7_day_sum,total_pediatric_patients_hospitalized_confirmed_covid_7_day_sum,inpatient_beds_7_day_sum,total_icu_beds_7_day_sum,total_staffed_adult_icu_beds_7_day_sum,icu_beds_used_7_day_sum,staffed_adult_icu_bed_occupancy_7_day_sum,staffed_icu_adult_patients_confirmed_and_suspected_covid_7_day_sum,staffed_icu_adult_patients_confirmed_covid_7_day_sum
0,2021-09-17,CO,KINDRED HOSPITAL-DENVER,DENVER,Long Term,81.0,81.0,48.0,44.7,44.7,...,0.0,0.0,0.0,336.0,28.0,28.0,0.0,0.0,0.0,0.0
1,2021-04-30,CO,NATIONAL JEWISH HEALTH,DENVER,Short Term,25.0,18.0,6.0,-999999.0,-999999.0,...,0.0,0.0,0.0,91.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2021-03-19,CO,KINDRED HOSPITAL AURORA,AURORA,Long Term,37.0,37.0,37.0,35.4,35.4,...,0.0,0.0,0.0,259.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2020-12-25,CO,CRAIG HOSPITAL,ENGLEWOOD,Long Term,88.0,88.0,88.0,86.1,86.1,...,0.0,0.0,0.0,616.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2020-12-11,CO,"ANIMAS SURGICAL HOSPITAL, LLC",DURANGO,Short Term,27.0,27.0,12.0,4.3,4.3,...,0.0,0.0,0.0,84.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5545,2020-07-31,CO,MEDICAL CENTER OF THE ROCKIES,LOVELAND,Short Term,197.0,197.0,197.0,143.3,143.3,...,27.0,0.0,0.0,1379.0,252.0,252.0,117.0,117.0,14.0,14.0
5546,2020-07-31,CO,EAST MORGAN COUNTY HOSPITAL,BRUSH,Critical Access Hospitals,25.0,25.0,25.0,-999999.0,-999999.0,...,0.0,0.0,0.0,175.0,28.0,28.0,-999999.0,-999999.0,0.0,0.0
5547,2020-07-31,CO,SWEDISH MEDICAL CENTER,ENGLEWOOD,Short Term,429.0,407.0,407.0,324.3,320.4,...,45.0,0.0,0.0,3003.0,623.0,476.0,449.0,429.0,36.0,11.0
5548,2020-07-31,CO,POUDRE VALLEY HOSPITAL,FORT COLLINS,Short Term,239.0,239.0,239.0,119.1,119.1,...,18.0,0.0,0.0,1673.0,238.0,238.0,66.0,66.0,17.0,17.0
5549,2020-07-31,CO,UNIVERSITY COLO HEALTH MEMORIAL HOSPITAL CENTRAL,COLORADO SPRINGS,Short Term,459.0,459.0,459.0,344.0,344.0,...,165.0,0.0,0.0,3213.0,427.0,427.0,318.0,318.0,25.0,21.0

In [152]:
'''
cases: All data of covid19 cases in US
states_data(dictionary type): All data of covid19 cases in one State
city(dictionary type): All data of covid19 cases in one city
vac_states(dictionary type): data of vaccine 
hosp(dictionary type):data of hospital
'''

selectByDate(hosp['OH'],"2020-01-22", "2021-05-24")

,Date,state,hospital_name,city,hospital_subtype,total_beds_7_day_avg,all_adult_hospital_beds_7_day_avg,all_adult_hospital_inpatient_beds_7_day_avg,inpatient_beds_used_7_day_avg,all_adult_hospital_inpatient_bed_occupied_7_day_avg,...,total_adult_patients_hospitalized_confirmed_covid_7_day_sum,total_pediatric_patients_hospitalized_confirmed_and_suspected_covid_7_day_sum,total_pediatric_patients_hospitalized_confirmed_covid_7_day_sum,inpatient_beds_7_day_sum,total_icu_beds_7_day_sum,total_staffed_adult_icu_beds_7_day_sum,icu_beds_used_7_day_sum,staffed_adult_icu_bed_occupancy_7_day_sum,staffed_icu_adult_patients_confirmed_and_suspected_covid_7_day_sum,staffed_icu_adult_patients_confirmed_covid_7_day_sum
4,2021-03-19,OH,KINDRED HOSPITAL LIMA,LIMA,Long Term,26.0,26.0,24.0,21.9,21.9,...,0.0,0.0,0.0,168.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2021-03-12,OH,EDWIN SHAW REHAB INSTITUTE,CUYAHOGA FALLS,Short Term,60.0,60.0,60.0,58.0,58.0,...,0.0,0.0,0.0,420.0,0.0,0.0,0.0,0.0,0.0,0.0
6,2021-02-19,OH,AULTMAN SPECIALTY HOSPITAL,CANTON,Long Term,13.0,13.0,13.0,12.7,12.7,...,0.0,0.0,0.0,91.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2021-02-05,OH,AULTMAN SPECIALTY HOSPITAL,CANTON,Long Term,13.0,13.0,13.0,11.0,11.0,...,0.0,0.0,0.0,91.0,0.0,0.0,0.0,0.0,0.0,0.0
8,2021-01-08,OH,AULTMAN SPECIALTY HOSPITAL,CANTON,Long Term,13.0,13.0,13.0,4.0,4.0,...,0.0,0.0,0.0,91.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11400,2020-07-31,OH,FAIRFIELD MEDICAL CENTER,LANCASTER,Short Term,259.7,256.3,171.6,121.0,120.9,...,70.0,0.0,0.0,1229.0,322.0,322.0,202.0,202.0,23.0,23.0
11401,2020-07-31,OH,CRYSTAL CLINIC ORTHOPAEDIC CENTER,AKRON,Short Term,61.0,61.0,61.0,24.0,23.0,...,0.0,0.0,0.0,427.0,0.0,0.0,0.0,0.0,0.0,0.0
11402,2020-07-31,OH,MERCY HEALTH - ST CHARLES HOSPITAL,OREGON,Short Term,337.1,291.3,291.1,148.1,146.0,...,30.0,0.0,0.0,2359.0,350.0,350.0,46.0,46.0,13.0,6.0
11403,2020-07-31,OH,AVITA ONTARIO,ONTARIO,Short Term,26.0,26.0,24.3,15.1,16.6,...,5.0,0.0,0.0,170.0,46.0,46.0,32.0,34.0,9.0,5.0
11404,2020-08-07,OH,WOOSTER COMMUNITY HOSPITAL,WOOSTER,Short Term,115.0,113.0,113.0,56.4,56.3,...,32.0,0.0,0.0,805.0,98.0,98.0,52.0,52.0,27.0,27.0

In [103]:


selectByDate(vac_states["CO"],"2021-01-22", "2021-02-24")

<ipython-input-103-827fc3f3f4c2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vac_states["CO"]["Date"] = vac_states["CO"]["Date"].apply(pd.to_datetime)
<ipython-input-103-827fc3f3f4c2>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vac_states["CO"]["Date"] = vac_states["CO"]["Date"].dt.strftime('%Y-%m-%d')

,Date,MMWR_week,Location,Distributed,Distributed_Janssen,Distributed_Moderna,Distributed_Pfizer,Distributed_Unk_Manuf,Dist_Per_100K,Distributed_Per_100k_12Plus,...,Series_Complete_Pfizer_12Plus,Series_Complete_Unk_Manuf_12Plus,Series_Complete_Janssen_18Plus,Series_Complete_Moderna_18Plus,Series_Complete_Pfizer_18Plus,Series_Complete_Unk_Manuf_18Plus,Series_Complete_Janssen_65Plus,Series_Complete_Moderna_65Plus,Series_Complete_Pfizer_65Plus,Series_Complete_Unk_Manuf_65Plus
14652,2021-02-23,8,CO,"1,417,245",0,0,0,0,"24,610",0,...,0,0,0,0,0,0,0,0,0,0
14684,2021-02-22,8,CO,"1,348,800",0,0,0,0,"23,422",0,...,0,0,0,0,0,0,0,0,0,0
14777,2021-02-21,8,CO,"1,348,800",0,0,0,0,"23,422",0,...,0,0,0,0,0,0,0,0,0,0
14843,2021-02-20,7,CO,"1,348,800",0,0,0,0,"23,422",0,...,0,0,0,0,0,0,0,0,0,0
14909,2021-02-19,7,CO,"1,332,775",0,0,0,0,"23,144",0,...,0,0,0,0,0,0,0,0,0,0
14918,2021-02-18,7,CO,"1,282,300",0,0,0,0,"22,267",0,...,0,0,0,0,0,0,0,0,0,0
14999,2021-02-17,7,CO,"1,230,425",0,0,0,0,"21,366",0,...,0,0,0,0,0,0,0,0,0,0
15043,2021-02-16,7,CO,"1,224,575",0,0,0,0,"21,265",0,...,0,0,0,0,0,0,0,0,0,0
15165,2021-02-15,7,CO,"1,210,475",0,0,0,0,"21,020",0,...,0,0,0,0,0,0,0,0,0,0
15213,2021-02-14,7,CO,"1,210,475",0,0,0,0,"21,020",0,...,0,0,0,0,0,0,0,0,0,0
15284,2021-02-13,6,CO,"1,210,475",0,0,0,0,"21,020",0,...,0,0,0,0,0,0,0,0,0,0
15338,2021-02-12,6,CO,"1,204,800",0,0,0,0,"20,921",0,...,0,0,0,0,0,0,0,0,0,0
15400,2021-02-11,6,CO,"1,162,775",0,0,0,0,"20,191",0,...,0,0,0,0,0,0,0,0,0,0
15473,2021-02-10,6,CO,"1,110,575",0,0,0,0,"19,285",0,...,0,0,0,0,0,0,0,0,0,0
15502,2021-02-09,6,CO,"1,045,000",0,0,0,0,"18,146",0,...,0,0,0,0,0,0,0,0,0,0
15579,2021-02-08,6,CO,"991,075",0,0,0,0,"17,210",0,...,0,0,0,0,0,0,0,0,0,0
15632,2021-02-07,6,CO,"991,075",0,0,0,0,"17,210",0,...,0,0,0,0,0,0,0,0,0,0
15683,2021-02-06,5,CO,"991,075",0,0,0,0,"17,210",0,...,0,0,0,0,0,0,0,0,0,0
15769,2021-02-05,5,CO,"989,075",0,0,0,0,"17,175",0,...,0,0,0,0,0,0,0,0,0,0
15810,2021-02-04,5,CO,"983,225",0,0,0,0,"17,074",0,...,0,0,0,0,0,0,0,0,0,0
15898,2021-02-03,5,CO,"940,800",0,0,0,0,"16,337",0,...,0,0,0,0,0,0,0,0,0,0
15954,2021-02-02,5,CO,"871,875",0,0,0,0,"15,140",0,...,0,0,0,0,0,0,0,0,0,0
16011,2021-02-01,5,CO,"813,400",0,0,0,0,"14,125",0,...,0,0,0,0,0,0,0,0,0,0
16103,2021-01-31,5,CO,"813,400",0,0,0,0,"14,125",0,...,0,0,0,0,0,0,0,0,0,0
16135,2021-01-30,4,CO,"813,400",0,0,0,0,"14,125",0,...,0,0,0,0,0,0,0,0,0,0
16224,2021-01-29,4,CO,"813,400",0,0,0,0,"14,125",0,...,0,0,0,0,0,0,0,0,0,0
16276,2021-01-28,4,CO,"806,950",0,0,0,0,"14,013",0,...,0,0,0,0,0,0,0,0,0,0
16326,2021-01-27,4,CO,"775,050",0,0,0,0,"13,459",0,...,0,0,0,0,0,0,0,0,0,0
16398,2021-01-26,4,CO,"726,450",0,0,0,0,"12,615",0,...,0,0,0,0,0,0,0,0,0,0
16470,2021-01-25,4,CO,"692,700",0,0,0,0,"12,029",0,...,0,0,0,0,0,0,0,0,0,0
16565,2021-01-24,4,CO,"692,700",0,0,0,0,"12,029",0,...,0,0,0,0,0,0,0,0,0,0
16583,2021-01-23,3,CO,"692,700",0,0,0,0,"12,029",0,...,0,0,0,0,0,0,0,0,0,0